{% set version = "0.0.15" %}
{% set sha256 = "e76adfd5b1eba6022f431e4e7d0f9193144c3de5ccd5e6361409532f08b79697" %}

package:
    name: scikit-beam
    version: {{ version }}

source:
    url: https://github.com/scikit-beam/scikit-beam/archive/v{{ version }}.tar.gz
    fn: scikit-beam-v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  script:
    - python setup.py build_ext -i
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - autoconf    # [osx]
        - {{ compiler('c') }}
    host:
        - python
        - setuptools
        - numpy
        - six
        - cython
    run:
        - python
        - {{ pin_compatible('numpy') }}
        - scipy
        - six
        - xraylib
        - scikit-image
        - lmfit 0.8.3

test:
    imports:
        - skbeam
        - skbeam.io
        - skbeam.core
        - skbeam.core.accumulators
        - skbeam.core.constants
        - skbeam.core.fitting
        - skbeam.core.fitting.base
        - skbeam.ext
        - skbeam.core.fitting
        - skbeam.core.constants.xrf
        # has linux native library imports  # [not win]
        - skbeam.ext.ctrans    # [not win]
    commands:
        # Don't need to specify path due to the CONDA_DEFAULT_ENV env var being set inside of conda-build
        # which is pointing to the test environment
        # These next two lines are currently failing due to an API change from conda-build 1.21.* -> 2.0.*
        #- conda inspect linkages scikit-beam  # [not win]
        #- conda inspect objects scikit-beam  # [osx]

about:
    home: http://scikit-beam.github.io/scikit-beam/
    license: BSD 3-Clause
    summary: Data analysis algorithms for X-Ray, Neutron and Electron sciences
    # Need to add LICENSE to the manifest
    # license_file: LICENSE
    license_family: BSD

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - tacaswell
        - CJ-Wright
